### ISSUE TITLE
Wide sequence diagrams get cut off

### ISSUE THREAD

**Issue by michaelomichael** [kensa-dev/kensa#25]
If your kensa output includes a sequence diagram that is wider than the browser window (see the screenshot below), then it is not possible to scroll horizontally to see the rest of the diagram.

![image](https://github.com/kensa-dev/kensa/assets/10383044/f5f24bbd-4fd6-4ac7-b86c-e59c7478085c)

I found this to be the case in Chrome (121.0.6167.85) and Firefox (121.0.1 64-bit) on OSX, using Kensa 0.4.13. Safari _does_ allow you to scroll right, but some bug there makes it extremely difficult to scroll left again afterwards!

It would be good if the container for the sequence diagram was horizontally scrollable. I'll submit a PR for this shortly.

**Comment by paul-brooks** [comment]
Thanks for raising this and for the PR.  I'll merge it over e weekend and release.
